version: 1.2
workflows:
  - name: AFI_16S_Main
    subclass: WDL
    primaryDescriptorPath: /wdl/AFI_16S_Main.wdl
    testParameterFiles:
      - /wdl/inputs/validation_single.example.json
      - /wdl/inputs/routine_single.example.json
  - name: AFI_16S_Batch
    subclass: WDL
    primaryDescriptorPath: /wdl/AFI_16S_Batch.wdl
    testParameterFiles:
      - /wdl/inputs/batch_mixed.example.json
